version: "3"

vars:
  PYTHON: uv run

tasks:
  default:
    desc: Show all available tasks
    cmds:
      - task --list-all
    silent: true
  install:
    desc: Install project dependencies
    cmds:
      - uv sync
  run:
    desc: Run the main application
    cmds:
      - "{{.PYTHON}} main.py"
  generate:
    desc: Generate data
    cmds:
      - "{{.PYTHON}} generate.py"
  cluster:
    desc: Run bipartite clustering analysis
    cmds:
      - "{{.PYTHON}} bipartite_clustering.py {{.CLI_ARGS}}"
  visualize:
    desc: Visualize clustering results
    deps:
      - cluster
    cmds:
      - "{{.PYTHON}} visualize_clusters.py"
  preview:
    desc: Open preview HTML in browser
    cmds:
      - open preview.html

